{% set version = "0.1.0" %}

package:
  name: modflow2netcdf
  version: {{ version }}

source:
  fn: modflow2netcdf-{{ version }}.tar.gz
  url: https://github.com/axiom-data-science/modflow2netcdf/archive/{{ version }}.tar.gz
  sha256: fa444a0962f4407c33354317b437fe9c4911f4bc74da3d314d8fbebeebb90f50
  patches:
    # See https://github.com/axiom-data-science/modflow2netcdf/issues/9
    - np_mpl_version.patch

build:
  number: 1000
  skip: True  # [py3k]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - matplotlib
    - scipy
    - pygc
    - netcdf4
    - pyproj
    - flopy
    - python-dateutil
    - pytz

test:
  requires:
    - pytest
  imports:
    - modflow2netcdf
  commands:
    - mod2net -h

about:
  home:  https://github.com/axiom-data-science/modflow2netcdf
  license: MIT
  summary: 'Converts Modflow Output files to CF Compliant NetCDF.'

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
