travis:
  secure:
    BINSTAR_TOKEN: SD29w8TrxP1kTPCYMiKUukhtSPnAGF1LJ7rgutH2VdtzWSuIivhxRbIszD0YHtdbQcMrz3B5tvyL+uY6dOmqO/WuKi60Nw5NnQc3ROBRdt/cRZUNGdQQbHle0WW7KkYCV76o4Hu9cPelQHk9BUrvcEjCrG3R/JDCIysZnOS2MBVas5qYxsmUul1gw5NhiKhc2N2rmtTioL0nBdIVtNuRM7sWSnZhzVsFhN61IFDNLZz5te+nr2cXy4V7eUMmMyueqfMIOoUNcknwjNymuLIQd7eAhmLS8qF8Rw1sWp/frwRWUiVVbhmB1tThoUSQctaI73B000mSHPYC0zhcrED3fpME5dsWXroSUkWEp3aQsw+VcK1Aa2cZuhHFqpH79gRKX1NXNMs26cFMrA/VVPQcDEImiGMjnIKFPUk0r8WrIgLDPH1XEatB00Dv3SpQ6QkRkOyRznxd6mCAcaI1cWltZR3ft58KUtYMuh5/TVEIuYwzyNtDwFLiBpIT73wkgmrunI3Qd5B/FrHPREfTTnDNvbS4thAtciMA+BD0H1ISfShYo/0+I7XfVFTspP8VJUpbT0lhPpSERnkaay8Chrfvm2H37ydcFntdZVZY6rahmcg9YcKTfn7Q5WOiGbQb0y4Tv4uUgqmH0KH/mEVVEhQo7WmXv2F6NcePuzHbuNVrL3k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
