travis:
  secure:
    BINSTAR_TOKEN: cyywgUFolooA5lfWJxgdjrDwL/VAvT0wfiCwsqAlSHgS9pWdWYKJdwZzsaUw/HgtHcbUG6BKQRQX/F2cvHOfyZjqFYdGY3o1q/iFWgf9jo8s5OxqltMtGWknn6YvY8EgLG2cngSC+NVLd3w/NQc9v5OJVdllpgw+w5AkIHTtYHpQK8Tz1IKDYENarGSKaBz+xaxM1HUUTvIz/weLP612JKUgl6svNQeU1ZK9l+IT5ipkS463Am7oDDhoNCTaTwqgwNmGX3JohMeE1j8dRfneLmooi+IbtruHlHkL7LyUqFu4UNdYIp1QLUa9Mh2Qqn5aRme1q6eNImKM/771h+kY8yNgTwulwy8EC0wg6AR4HBjANxC2dlLgH5n1oOZgTP9AOqvau9/k0rei0AVhzv9O02l0b5zz3waICtmxEQxNzCww510FIltRKje7r3Ow49IBoFM7TZ5VM8dK4GFy62C7UJyXyINIh+iNm141PvjQl33ia7ZuHihLAkhCIFohRaubz7i/qXtaWD06JRO83tiutWQgfwRJVDMRPKGVmqEMN420BlFah/BqKY+IPRxVPXpqD795+uSX1ARg/QVaFSZkKKbyQ5jzRQQRsnBb9NTargGa+ENwtKdQ//I0WQV0Z42Vq49ShTXRTM921a5NIxLO6iQy/7kKzmBW0MyV4XKQG+E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
